/**
 * Pure Java console application.
 * This application demonstrates console I/O.
 *
 * This file was automatically generated by
 * Omnicore CodeGuide.
 */

// Variables: time: ms; distance: nm; force: pN


public class ChristiansSim
{
	/**
	 * This method is called after start up.
	 *
	 * @param args   The command-line arguments.
	 *               They can be changed in the
	 *               "Project Settings" dialog in CodeGuide.
	 */
	/*public static void main(String[] args)
	{
		MainLoop m=new MainLoop();
		
		// Print application prompt to console.
		System.out.println("ChristiansSim");
		
		// Print available command-line arguments to console.
		printArguments(args);
		
		m.run(1000);
		
		// Read user input from console.
		System.out.println("Press ENTER to continue.");
		readInput();
	 }*/
	
	/**
	 * This method prints available command-line arguments
	 * to the console.
	 */
	private static void printArguments(String[] args)
	{
		for (int i = 0; i < args.length; i++)
		{
			System.out.print("Argument " + i + ": ");
			System.out.println(args[i]);
		}
		
	}
	
	/**
	 * This method reads user input from console.
	 */
	private static void readInput()
	{
		try
		{
			// Wait for console input.
			System.in.read();
		}
		catch (java.io.IOException e)
		{
			// An error occured.
			System.err.println("Error while reading input.");
		}
	}
}
